version: '3.7'
services: 
    mqtt:
        image: eclipse-mosquitto
        ports:
            - 1883
        links: 
            - app
        
    mongodb:
        image: mongo
        restart: always
        ports: 
            - 27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: germany
            MONGO_INITDB_ROOT_PASSWORD: germany
            MONGO_INITDB_DATABASE: primedb
        links: 
            - app
        
    app:
        build: .
        
        
networks:
    default:
        external: 
            name: timber
    


